# Generated by Django 3.0.3 on 2020-03-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
