# Generated by Django 3.0.3 on 2020-03-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20200311_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
