# Generated by Django 3.0.3 on 2020-03-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importexl',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='importexl',
            name='document',
        ),
    ]
